filename=share-in-group-08-17

slides:
	pandoc -s --mathjax -i --self-contained -t revealjs main.md -o $(filename).html
	# pandoc -s --mathjax --self-contained -t revealjs main.md -o $(filename).html
